### ISSUE TITLE
[Feature Request] Adding a single colon would already improve pubspec.yaml integration flow

### ISSUE THREAD

**Issue by craigomac** [dart-lang/pub-dev#3564] opened 2020-04-25 09:10 UTC
This might seem ridiculous, but adding a single colon and (optionally) a "copy" button at the top beside a package name would save valuable seconds for millions of developers every day. A very common use case is to copy the package name into pubspec.yaml, but it's always fiddly because you have to go in and put the colon there, or else copy the name, tab back to the browser because you already forgot the latest version, then tab back (etc. etc.).

So how about it, a quick win for the lazy developer community?

![image](https://user-images.githubusercontent.com/6972172/80275938-271bfd80-86e5-11ea-9f67-488872916e72.png)

**Comment by isoos** [comment] 2020-04-25 16:57
@craigomac: thanks for the suggestion! If you don't mind, I'd close this as the duplicate of #3336.

**Closed by isoos** 2020-04-25 16:57 UTC

**Comment by bean5** [comment] 2020-05-08 22:55
Although a duplicate, I like the image implementation. Simple, clean, nearly as elegant as what is present.

**Comment by bean5** [comment] 2020-05-08 22:56
@craigomac could you post that picture on #3336 ?
