### ISSUE TITLE
List license as 'pending' before analysis

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#6950] opened 2023-08-22 10:26 UTC
When a package is awaiting analysis, we show the license as "unknown". I think we should show it as "pending" similar to other analysis driven data. Example:

<img width="1167" alt="Screenshot 2023-08-22 at 12 25 25" src="https://github.com/dart-lang/pub-dev/assets/13644170/8ad67f33-090b-4f54-bc71-24aab2c8a116">

**Comment by natsuk4ze** [comment] 2023-08-24 04:57
I think this is a duplicate of #6953

**Closed** 2023-09-06 12:38 UTC
Labels: Type: bug
