### ISSUE TITLE
[Feature] Exclude supports for certain platform

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/pub-dev#4602] opened 2021-03-12 09:13 UTC
https://pub.dev/packages/libusb supports only Windows/macOS/Linux

Could we exclude the `TAG`s of Android/iOS?

<img width="701" alt="Screen Shot 2021-03-12 at 3 49 09 PM" src="https://user-images.githubusercontent.com/7928961/110918474-2c625500-8356-11eb-9c23-8418c755124e.png">

BTW: `libusb` is a Dart package, neither Flutter plugin nor Flutter package. None of it dependency declared something like:

```yaml
flutter:
  plugin:
    platforms:
      android: xxx
      ios: xxx
```

**Comment by isoos** [comment] 2021-03-12 09:30
@Sunbreak: can you think of any intrinsic property inside the package that we can detect and could suggest us that it supports desktop platforms only?

**Comment by Sunbreak** [comment] 2021-03-12 10:19
Maybe something like:

```yaml
dart:
  native:
    platforms: [windows, linux, macos]
```

**Comment by isoos** [comment] 2021-03-12 10:30
@Sunbreak: I was thinking if there is in the code, the dependencies, in the layout of the project or in the content of the files that necessarily excludes mobile platforms. We tend to prefer inferring these as opposed to requiring to specify explicitly.

**Comment by Sunbreak** [comment] 2021-03-12 10:35
`libusb` is quite basic. It only depends on the libusb-1.0.dll/dylib/so

I don't think it is could be inferred from the code , the dependencies or the layout of the project. `pubspec.yaml` is the only thing comes up with

**Comment by stuartmorgan** [comment] 2021-03-12 23:59
In general, there's unlikely to be a way to detect platform limitation of a package whose limitation comes from either FFI or `Process` calls.

**Comment by sigurdm** [comment] 2022-01-27 09:56
This has been fixed in pana already, and will show up in a coming pub release.

Closing as a duplicate of https://github.com/dart-lang/pana/issues/889

**Closed by sigurdm** 2022-01-27 09:56 UTC
