### ISSUE TITLE
Show WASM support tag for libraries

### ISSUE THREAD

**Issue by amrgetment** [dart-lang/pub-dev#7279] opened 2023-12-10 07:33 UTC
I wonder if you could add a tag to show if a library supports WASM for web or not?

![image](https://github.com/dart-lang/pub-dev/assets/149420647/532018d3-b2d7-4ba3-902c-7fe4b5743917)

**Comment by amrgetment** [comment] 2023-12-10 07:36
And add it in filter section

**Comment by sigurdm** [comment] 2023-12-11 09:08
I think we should.

How do we know/detect if a package supports wasm?

I guess it should really be another platform: `Platforms | android ios macos web wasm`.

**Comment by amrgetment** [comment] 2023-12-11 09:42
@sigurdm wasm is a render mode not another platform

`flutter run --help`

```
    --web-renderer                          The renderer implementation to use
                                                             when building for the web.

          [auto] (default)                     Use the HTML renderer on mobile
                                                             devices, and CanvasKit on desktop
                                                             devices.

          [canvaskit]                             Always use the CanvasKit renderer.
                                                             This renderer uses WebGL and
                                                             WebAssembly to render graphics.
          [html]                                       Always use the HTML renderer. This
                                                             renderer uses a combination of HTML,
                                                             CSS, SVG, 2D Canvas, and WebGL.
          [skwasm]                                Always use the experimental skwasm
```

How do we know/detect if a package supports wasm? @kevmoo

**Comment by sigurdm** [comment] 2023-12-11 10:16
From a runtime/compilation mode-perspective it is another platform though... but not sure how we want to present it to the end user...

**Comment by kevmoo** [comment] 2023-12-11 22:34
Duplicate of https://github.com/dart-lang/pub-dev/issues/6785

**Closed by kevmoo** 2023-12-11 22:34 UTC
Labels: Type: enhancement
