### ISSUE TITLE
Need sorting by functionality, ui etc.

### ISSUE THREAD

**Issue by abinvs-2019** [dart-lang/pub-dev#6121] opened 2022-10-19 08:52 UTC
Need a feature to sort packages by its nature like Functionality, Ui and Animations, Game development, pay integrations, etc.
Would be useful for searching and picking the right one.

**Comment by abinvs-2019** [comment] 2022-10-19 08:54
@domesticmouse can this be implemented?

**Comment by isoos** [comment] 2022-10-19 09:14
Closing this, as it looks like a duplicate of the category classification of #5219.

**Closed by isoos** 2022-10-19 09:14 UTC
