### ISSUE TITLE
[Question] How to measure the doc coverage like pub.dev did to packages

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#6876] opened 2023-08-01 03:09 UTC
Related docs:
- https://pub.dev/help/scoring
- https://dart.dev/guides/libraries/create-packages#documenting-a-library

The above docs didn't explain how to measure the coverage of the package, it can be explained in detail for package authors to improve their documents.

**Comment by sigurdm** [comment] 2023-08-10 09:07
Closing as a duplicate of https://github.com/dart-lang/pana/issues/1229 .

**Closed by sigurdm** 2023-08-10 09:07 UTC

**Comment by AlexV525** [comment] 2023-08-10 09:24
Sorry but can you explain more about the duplicate? I don't see its subset contains the info I required.

**Comment by isoos** [comment] 2023-08-10 09:46
We are planning to (a) move the relevant parts from `dart-lang/pub-dev/pkg/pub_dartdoc` into `dart-lang/dartdoc`, and (b) when that happens, pana will be able to expose it and produce the same output as `pub.dev`. (In another perspective: pub.dev will use an unmodified pana to create the reports.)

**Comment by AlexV525** [comment] 2023-08-10 10:15
So `dartdoc` would have a direct command to calculate doc coverage, right?

**Comment by isoos** [comment] 2023-08-10 11:21
> So dartdoc would have a direct command to calculate doc coverage, right?

It should have a CLI flag that also outputs the coverage data somewhere.

**Comment by AlexV525** [comment] 2023-08-10 11:46
> It should have a CLI flag that also outputs the coverage data somewhere.

Thanks! Good to know.
