### ISSUE TITLE
Search from api docs broken

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#3328] opened 2020-02-17 09:00 UTC
Searching for `Text` from https://pub.dev/documentation/markdown/latest/markdown/HorizontalRuleSyntax-class.html

Gives this link:
https://pub.dev/documentation/markdown/latest/markdown/markdown/Text-class.html

That is a 404

Searching from https://pub.dev/documentation/markdown/latest/index.html
Gives the working link:

https://pub.dev/documentation/markdown/latest/markdown/Text-class.html

**Comment by isoos** [comment] 2020-02-17 11:33
This looks like an issue with the base URLs: both pages link to `markdown/Text-class.html` (referenced in the [dartdoc index](https://pub.dev/documentation/markdown/latest/index.json)), which is a relative link to the current page, and because of that, the in-library page will duplicate the library name in the URL.

@jcollins-g: Could you please take a look at it and confirm?

**Comment by jonasfj** [comment] 2020-02-19 09:55
I can't reproduce this with dartdoc locally.

**Comment by isoos** [comment] 2020-02-19 13:04
Confirmed:
- current prod is on `dartdoc 0.30.0+1`, which has the broken behaviour
- this was fixed in https://github.com/dart-lang/dartdoc/pull/2125
- fix is part of `dartdoc 0.30.1`, which is now the content served on staging (and local dev)

**Closed by isoos** 2020-02-19 13:04 UTC
Labels: Type: bug
