### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Aruljebaraj** [dart-lang/pub-dev#7633] opened 2024-04-10 06:38 UTC
<img width="1470" alt="Screenshot 2024-04-10 at 12 08 16 pm" src="https://github.com/dart-lang/pub-dev/assets/34904782/eb14c7ab-a6d1-4e47-b3b2-b8902ca6991e">
![Screenshot 2024-04-10 at 12 08 16 pm 2](https://github.com/dart-lang/pub-dev/assets/34904782/daaecc7d-cbc1-4f07-9094-4b05e06ea607)

**Comment by jonasfj** [comment] 2024-04-10 10:54
Thanks for reporting this!

Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/7624

**Closed by jonasfj** 2024-04-10 10:54 UTC
