### ISSUE TITLE
Incorrect tagging for Flutter web (old style plugins)

### ISSUE THREAD

**Issue by shptecheu** [dart-lang/pub-dev#3689] opened 2020-06-05 19:19 UTC
URL: https://pub.dev/packages
Filter: Flutter web

I have been struggling to find packages that _really_ support Flutter Web. Generally, compatible packages have a readme with a section for Android, iOS and Web.

However, I found most packages were ticking Web arbitrarily and when trying them out, they do not really work. Moreover, Flutter debug is not attaching and can't really drill down.

So i guess, I do not know if I understand what the tag is supposed to mean or maybe it needs some governance to prove the package is actually supporting the platform.

In case of the former, I am sorry for the inconvenience and I will close the issue right away. I am new to flutter, so maybe i do not understand how the ecosystem works so far, so take my rant with a grain of salt. I do not mean any offense, just my experience as a newbie.

**Comment by sigurdm** [comment] 2020-06-08 08:37
The platform tagging could surely be improved  so no offense taken.
But could you provide us with concrete examples with packages that are declared to work on flutter-web but did not work when you tried it?
Also what went wrong?
Perhaps some packages don't work as intended.
And please give your `flutter doctor` output.

**Comment by shptecheu** [comment] 2020-06-08 16:09
One of the earliest packages I tried was  [flutter_email_sender](https://pub.dev/packages/flutter_email_sender). Granted, there were open issues regarding similar behaviour, case in point [flutter_email_sender Issue #43](https://github.com/sidlatau/flutter_email_sender/issues/43).

Most of the packages were tagged for web, but had the same generic error of "Overflow on channel: _<packageName>_.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel."

Other ones like [share_extend ](https://pub.dev/packages/share_extend) and [flutter_share](https://pub.dev/packages/flutter_share) are missing the web directory in the source but still tagged as Web.

I'm hoping there is a stopgap solution like removing auto tagging for Web until we can tackle this in a more elegant way. It would be less frustrating to get started and hopefully beneficial to the community to keep the tagging accurate.


### Flutter Doctor output as requested:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.16299.522], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.45.1)
[√] Connected device (2 available)

• No issues found!

**Comment by jonasfj** [comment] 2020-06-09 09:15
Ah, this is probably -> https://github.com/dart-lang/pana/issues/639

**Comment by sigurdm** [comment] 2020-06-11 12:02
A new version has been deployed yesterday.

https://pub.dev/packages/flutter_email_sender, https://pub.dev/packages/share_extend and https://pub.dev/packages/flutter_share is now no longer marked as web!

**Closed by sigurdm** 2020-06-11 12:02 UTC
