### ISSUE TITLE
Error: Connection closed before full header was received

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3192] opened 2019-12-19 09:32 UTC
Not sure why this happens, maybe we're exceeding some deadline and closing down connections?
Looks as though this is happening when talking to GCS.

Stack trace looks like:
```
pub.job: dartdoc job error dbutils 1.1.0

Error:
    Connection closed before full header was received

Stack:
    #0      IOClient.send (package:http/src/io_client.dart:65:7)
    <asynchronous suspension>
    #1      AuthenticatedClient.send (package:googleapis_auth/src/auth_http_utils.dart:28:37)
    <asynchronous suspension>
    #2      _MetadataServerClient.send (package:googleapis_auth/auth_io.dart:349:25)
    <asynchronous suspension>
    #3      RetryClient.send (package:http_retry/http_retry.dart:97:33)
    <asynchronous suspension>
    #4      ApiRequester._request.simpleRequest (package:_discoveryapis_commons/src/clients.dart:227:26)
    #5      ApiRequester._request (package:_discoveryapis_commons/src/clients.dart:256:25)
    #6      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:71:26)
    <asynchronous suspension>
    #7      ObjectsResourceApi.delete (package:googleapis/storage/v1.dart:2990:32)
    #8      _BucketImpl.delete (package:gcloud/src/storage_impl.dart:235:25)
    #9      deleteFromBucket (package:pub_dev/shared/storage.dart:36:18)
    <asynchronous suspension>
    #10     DartdocBackend._deleteAllWithPrefix.<anonymous closure> (package:pub_dev/dartdoc/backend.dart:381:33)
    #11     Pool.withResource (package:pool/pool.dart:127:28)
    <asynchronous suspension>
    #12     DartdocBackend._deleteAllWithPrefix (package:pub_dev/dartdoc/backend.dart:381:14)
    #13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #14     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #16     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #17     _rootRunUnary (dart:async/zone.dart:1134:38)
    #18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #19     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #21     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #22     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #25     ApiRequester.request (package:_discoveryapis_commons/src/clients.dart)
    #26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #27     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #28     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #29     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #30     _rootRunUnary (dart:async/zone.dart:1134:38)
    #31     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #32     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #34     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #35     Future._complete (dart:async/future_impl.dart:514:7)
    #36     Stream.join.<anonymous closure> (dart:async/stream.dart:844:18)
    #37     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #38     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #39     _rootRun (dart:async/zone.dart:1122:38)
    #40     _CustomZone.run (dart:async/zone.dart:1023:19)
    #41     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #42     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #43     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #44     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #45     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
    #46     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
    #47     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
    #48     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
    #49     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
    #50     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
    #51     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #52     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #53     _rootRun (dart:async/zone.dart:1122:38)
    #54     _CustomZone.run (dart:async/zone.dart:1023:19)
    #55     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #56     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #57     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #58     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #59     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
    #60     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
    #61     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #62     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #63     _rootRun (dart:async/zone.dart:1122:38)
    #64     _CustomZone.run (dart:async/zone.dart:1023:19)
    #65     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #66     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #67     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #68     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #69     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
    #70     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
    #71     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #72     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #73     _rootRun (dart:async/zone.dart:1122:38)
    #74     _CustomZone.run (dart:async/zone.dart:1023:19)
    #75     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #76     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #77     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #78     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #79     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
    #80     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
    #81     _StreamController.close (dart:async/stream_controller.dart:624:5)
    #82     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1039:23)
    #83     _HttpParser._doParse (dart:_http/http_parser.dart:777:15)
    #84     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
    #85     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
    #86     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #87     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #88     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #89     _rootRunUnary (dart:async/zone.dart:1134:38)
    #90     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #91     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #92     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
    #93     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
    #94     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
    #95     _StreamController._add (dart:async/stream_controller.dart:642:7)
    #96     _StreamController.add (dart:async/stream_controller.dart:588:5)
    #97     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
    #98     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #99     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #100    StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #101    _rootRunUnary (dart:async/zone.dart:1134:38)
    #102    _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #103    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #104    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
    #105    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
    #106    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
    #107    _StreamController._add (dart:async/stream_controller.dart:642:7)
    #108    _StreamController.add (dart:async/stream_controller.dart:588:5)
    #109    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1018:19)
    #110    StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #111    StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #112    _rootRun (dart:async/zone.dart:1122:38)
    #113    _CustomZone.run (dart:async/zone.dart:1023:19)
    #114    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #115    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #116    StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #117    StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #118    _rootRun (dart:async/zone.dart:1126:13)
    #119    _CustomZone.run (dart:async/zone.dart:1023:19)
    #120    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
    #121    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
    #122    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
    #123    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
    #124    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by isoos** [comment] 2024-07-19 12:12
Closing as duplicate of #7825.

**Closed by isoos** 2024-07-19 12:12 UTC
Labels: Area: stackdriver error report
