### ISSUE TITLE
Spamming pub.dev website 

### ISSUE THREAD

**Issue by sparkmobi** [dart-lang/pub-dev#3993] opened 2020-09-05 04:36 UTC
URL: https://pub.dev/packages/new_free_v_bucks_fortnite_generator_checker_codes_skins_tool/versions

<Describe your issue or suggestion here>

Spamming pub.dev website

**Comment by jonataslaw** [comment] 2020-09-05 06:01
There is already an open issue dealing with this, https://github.com/dart-lang/pub-dev/issues/3991 so it could be closed.
However, Spam has been available for 10 hours, we are unable to see new packages, so I hope this will be resolved soon.

**Comment by kaumudpa** [comment] 2020-09-06 15:01
Somebody is still spamming it, some spam packages were added at the time of this comment.

**Comment by jonasfj** [comment] 2020-09-07 10:37
Thanks for reporting, we are aware and working mitigate this problem.

**Comment by CiriousJoker** [comment] 2020-09-07 12:01
Another one:
https://pub.dev/packages/watch_brahms_the_boy_2_2020_full_hd_movie_online_free

**Comment by isoos** [comment] 2020-09-08 07:59
Closing this as the duplicate of #3991.

**Closed by isoos** 2020-09-08 07:59 UTC
