### ISSUE TITLE
Pub not loading 

### ISSUE THREAD

**Issue by RitikShaw** [dart-lang/pub-dev#4491] opened 2021-02-04 07:41 UTC
Requested URL: https://pub.dev/packages?q=spinkit
Request ID: 71e608802726f33b5359718b9cf164e2

**Comment by jonasfj** [comment] 2021-02-04 12:11
Thanks for the report :+1: 

The issue should be resolved, closing as duplicate of https://github.com/dart-lang/pub-dev/issues/4485

**Closed by jonasfj** 2021-02-04 12:11 UTC
Labels: Resolution: duplicate
