### ISSUE TITLE
Can't use spread operator inside ternary operator

### ISSUE THREAD

**Issue by adenzu** [dart-lang/pub-dev#5440] opened 2022-01-19 12:19 UTC
* Spread operator is unusable inside ternary operator.
 * https://media.discordapp.net/attachments/496003658866098187/933331058630488064/unknown.png

```dart
void main(){
    List a = [1, 2, 3];
    a.addAll([a.isEmpty ? 0 : ...a.map((e) => (e+1))]);
}
```

**Comment by eernstg** [comment] 2022-01-19 13:03
This is working as intended: The spread operator can be used on an `<element>`, and they can occur in a `<setOrMapLiteral>` and in a `<listLiteral>` (as a top-level term specifying "one element contribution" to the collection, which might be a single element, `<expressionElement>`, or several, `<spreadElement>`).

But you can move the spread operator:

```dart
void main() {
  List a = [1, 2, 3];
  a.addAll([
    ...(a.isEmpty ? [0] : a.map((e) => (e + 1)))
  ]);
}
```

**Comment by eernstg** [comment] 2022-01-19 13:09
I'll close this issue because it does not indicate that anything is working incorrectly. Also, if there is an issue with the language Dart or its tool chain then the best location to create an issue is the [Dart language repo](https://github.com/dart-lang/language/issues) respectively the [Dart SDK repo](https://github.com/dart-lang/sdk/issues).

**Closed by eernstg** 2022-01-19 13:09 UTC

**Comment by rakudrama** [comment] 2022-01-19 17:29
You can use `if`...`else` in a list literal
```
  [if (a.isEmpty) 0 else ...a.map((e) => (e+1))]
```
