### ISSUE TITLE
Pub is not feeling well. Fatal package site error.

### ISSUE THREAD

**Issue by FacuPapayannis** [dart-lang/pub-dev#7627] opened 2024-04-10 02:30 UTC
Requested URL: https://pub.dev/packages?q=gpt
Request ID: 20bc83aa69c8620d9bb3a8f12a7f6abb

**Comment by jonasfj** [comment] 2024-04-10 03:16
Thanks for reporting this!

Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/7624

**Closed by jonasfj** 2024-04-10 03:16 UTC
Labels: Resolution: duplicate
