### ISSUE TITLE
Package test showing as [UNIDENTIFIED] - why?

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub-dev#1355] opened 2018-06-07 17:19 UTC
URL: https://pub.dartlang.org/packages/test#-analysis-tab-

Thanks :)

**Comment by isoos** [comment] 2018-06-07 17:33
It started with `test` version `0.12.36`, and it seems like a bug in `pana`, which for some reason does not calculate the package-level platform information for this package. Looking into it.

**Comment by isoos** [comment] 2018-06-07 18:57
Root cause:
- `package:test` started to [expose](https://github.com/dart-lang/test/pull/820) bootstrap methods as part of its public API (with the 0.12.36 version), and `pana` identified that [`browser.dart`](https://github.com/dart-lang/test/blob/master/lib/bootstrap/browser.dart) is using `html`, `js`, `io`, and `isolate` components.
- `package:pana`, from version `0.10.6` started to treat `isolate` in conflict with the web platform, and identified the above file as one with platform conflict.
- Our current package-level platform classification logic will stop on the first file that has a platform conflict. Unfortunately, we fail to expose the related details in the analysis.

Which also concludes that only a small number of packages may have been affected by it.

Fixing the part where we don't expose the reason is easy, however, I'm wondering:

- Should we block package-level classification if any of the files have platform conflicts? (Or should we block only if the primary library has conflict?)

- Even if we fix the above, the analysis would classify `package:test` as `Flutter, other`. Should we add `web` with a custom override?

/cc @kevmoo, @mit-mit, @sortie

**Comment by kevmoo** [comment] 2018-06-07 20:00
https://github.com/dart-lang/test/blob/984ed9b11a501fc7cc26c369516d2fb15b2fc186/lib/src/runner/browser/platform.dart#L53-L54

If this just boils down to getting the favicon URL, we can certainly find a work-around here...

**Comment by isoos** [comment] 2018-06-08 08:20
> If this just boils down to getting the favicon URL, we can certainly find a work-around here...

Yes, it looks like that `test` is using `dart:isolate` only for that URL resolution, which I guess can be done in different ways.

**Comment by mit-mit** [comment] 2018-06-29 12:23
@isoos is there more work here?

**Comment by isoos** [comment] 2018-06-29 12:28
> @isoos is there more work here?

Most of the coding is done, but the `pana` changes have not reached the pub site yet. Keeping this open until it happens.

**Comment by timsneath** [comment] 2018-10-26 03:32
@rajeshzmoke can you try removing the last line in your `pubspec.yaml` file and try uploading again:

Specifically, this setting under the `environment` section:

```yaml
flutter: ">=0.1.2 <2.0.0"
```

**Comment by rajeshzmoke** [comment] 2018-10-26 07:28
> @rajeshzmoke can you try removing the last line in your `pubspec.yaml` file and try uploading again:
> 
> Specifically, this setting under the `environment` section:
> 
> ```yaml
> flutter: ">=0.1.2 <2.0.0"
> ```

i added that after i had this issue..

**Comment by mit-mit** [comment] 2018-10-26 07:34
@isoos can you take a look? If I download https://storage.googleapis.com/pub-packages/packages/flutter_date_picker-0.1.5.tar.gz and fun `flutter analyze`, that works as expected.

**Comment by isoos** [comment] 2018-10-26 07:35
@rajeshzmoke: this is being tracked in #1728. We think we know the root cause, you don't need to do anything at this point, the health score and the platform classification will be fixed once we patch the issue and release a new version of the pub site.

**Comment by rajeshzmoke** [comment] 2018-10-26 07:39
@isoos  Thank you.

**Comment by nipunasudha** [comment] 2021-03-10 17:16
Why does this happen even after two years?
![image](https://user-images.githubusercontent.com/17500323/110669515-6c102c00-81f2-11eb-8f60-0d478a8e94a7.png)

**Comment by c1avie** [comment] 2022-01-10 11:47
I have the same problem。  see   https://pub.dev/packages/tencent_trtc_cloud
![image](https://user-images.githubusercontent.com/2912208/148761046-065fd558-9e89-4873-b3a8-99d137f85426.png)

**Comment by c1avie** [comment] 2022-01-10 11:48
@kevmoo   PUB POINTS is 130

**Comment by sigurdm** [comment] 2022-01-10 12:42
@c1avie here is what I see:
![image](https://user-images.githubusercontent.com/8613953/148767578-1018e089-9cdf-4b10-973f-759e5665d295.png)

A package has to undergo analysis before it can show up with platforms, that usually takes a little while...

**Comment by c1avie** [comment] 2022-01-11 02:37
Strangely, it's all  ' [UNIDENTIFIED]' on our side。And the same is that we use vpn.

**Comment by sigurdm** [comment] 2022-01-11 08:34
We have found out that it is [unidentified] when not logged in, and has the platforms when logged in.

There is certainly some bug here - but we are still not sure what is happening. If it was an old cached value the cache should have expired within ~1 hour...

**Comment by isoos** [comment] 2022-07-26 17:53
Closing as no longer relevant.

**Closed by isoos** 2022-07-26 17:53 UTC
Labels: Area: site feedback, Type: quality
