### ISSUE TITLE
Dark mode for  pub.dev and flutter.dev

### ISSUE THREAD

**Issue by 10urb** [dart-lang/pub-dev#5563] opened 2022-03-08 15:55 UTC
URL: https://pub.dev/

Hi you guys. I usually work after evening then when click on pub.dev my eyes scream all the time. Can you add features dark mode or something? Please.

**Comment by isoos** [comment] 2022-03-08 16:59
This is a duplicate of #4416.

**Closed by isoos** 2022-03-08 16:59 UTC
