### ISSUE TITLE
Package name ... is too similar to another active package

### ISSUE THREAD

**Issue by kwado-tech** [dart-lang/pub-dev#7330] opened 2023-12-21 18:15 UTC
**The Issue**
####
I previously published a couple of packages to pub.dev and trying to update these package (running `flutter pub publish`) resulted to the below error message. 

I tried re-authenticating pub.dev with the same credentials used in publishing the said packages a number of times but this resulted to the same error message each time.

```text
Package name `l10n_mapper_annotation` is too similar to another active package: `l10n_mapper_annotation` (https://pub.dev/packages/l10n_mapper_annotation).
```

This seems to be an issue as republication (running `flutter pub publish`) should update the said packages with the new specified version-number, updates and fixes.

Below are the listed packages
- https://pub.dev/packages/l10n_mapper_annotation
- https://pub.dev/packages/l10n_mapper_generator

**Comment by isoos** [comment] 2024-01-05 09:31
@kwado-tech: Does the problem still exist? I'm trying to recreate the `l10_mapper_annotation` moderation + publishing this locally, and I cannot reproduce the error message.

**Comment by kwado-tech** [comment] 2024-01-05 09:57
@isoos The problem still exists. I just re-authenticated pub with two of my package publisher-credentials to publish updates to https://pub.dev/packages/l10n_mapper_annotation but got the same error massage.

I recently applied for the removal of a similar name package before publishing these. Probably this might be related or be of help?

**Comment by isoos** [comment] 2024-01-05 10:07
@kwado-tech: I was able to reproduce parts of the issue now, and not yet sure why this inconsistency was able to happen, but it looks like we have a tombstone conflict in the database. Did you have `l10n_mapper_annotation` published, deleted (by admins) and then re-published?

**Comment by kwado-tech** [comment] 2024-01-10 11:30
Hey @isoos, whats the progress on this issue? I see two related PRs merged but not sure what a conclusive resolve is.

**Comment by isoos** [comment] 2024-01-10 11:54
@kwado-tech: there will be a new site release this week, if it gets stable, one of the admins will remove/merge the Datastore entity that caused the issue.

**Comment by kwado-tech** [comment] 2024-01-11 03:12
Thanks @isoos I'll be on a lookout for this

**Comment by sigurdm** [comment] 2024-01-12 08:52
Should be fixed now. Please try again!

**Closed by sigurdm** 2024-01-12 08:52 UTC
Labels: Type: bug

**Comment by isoos** [comment] 2024-01-12 08:57
Note: thinking about it, it may be that `nameTracker` caches do not detect the removal of the `ModeratedPackage` entity, and success may depend on whether the instance has been restarted since the removal.

**Comment by kwado-tech** [comment] 2024-01-12 09:02
Thanks @isoos but apparently, I still notice the same error indicated fix. Perhaps this is could be a resulting from `nameTracker` cache not invalidate/restarted?

**Comment by sigurdm** [comment] 2024-01-12 09:06
@isoos do we have a way of restarting the nametracker?

**Comment by isoos** [comment] 2024-01-12 09:08
This is unfortunate, but `nameTracker` will only get restarted when the instance is restarted. In retrospect we should have done a rolling restart every few hours or so...

**Comment by kwado-tech** [comment] 2024-01-12 13:54
@isoos @sigurdm any work-around to resolve this?

**Comment by kwado-tech** [comment] 2024-01-12 16:23
Thanks guys @isoos @sigurdm . I was able to publish an update for https://pub.dev/packages/l10n_mapper_annotation but https://pub.dev/packages/l10n_mapper_generator still returns the same error

**Comment by sigurdm** [comment] 2024-01-15 13:02
I ran the tool on the mapper_generator package also. After the instance restarts it should also be available

**Comment by kwado-tech** [comment] 2024-01-15 23:01
Thanks guys this is resolved and works as expected @isoos @sigurdm
