### ISSUE TITLE
Please add search bar in detail packages

### ISSUE THREAD

**Issue by febritecno** [dart-lang/pub-dev#3860] opened 2020-07-20 12:41 UTC
i'm use new design of pub-dev site so wonderful UI. but, i'm so bad lucky when read detail packages and then will searching other packages. oh no search bar not found. i'm back to landing site it's so many of my time turn to wasted.

URL: https://pub.dev/packages/pogo

**Comment by isoos** [comment] 2020-07-20 12:44
@febritecno: when visiting a package page from search we do display this link:

<img width="227" alt="Screenshot 2020-07-20 at 14 43 18" src="https://user-images.githubusercontent.com/4778111/87938722-47b2e400-ca97-11ea-9a6e-b7c7b81f4348.png">

Is it visible for you? If not, could you please share your environment / setup? Maybe some content/privacy blocker is removing the referrer headers / blocking the JS?

**Comment by febritecno** [comment] 2020-07-20 13:33
@isoos 
I wish there was a search box in the package details. very easy for users to move to another package without returning to its original appearance. it's very tiring. but often the back button doesn't load properly either.

![image](https://user-images.githubusercontent.com/9696688/87943468-48b03980-cac8-11ea-9f8c-b4abb429d917.png)

**Comment by dmvvilela** [comment] 2020-07-20 13:41
I did not see this back to search button either.. But still, you have to have one more click to be able to search. I think it would be usefull to have a search bar right there in the nav bar.

**Comment by febritecno** [comment] 2020-07-21 11:48
@dmvvilela  i think same with you.

**Comment by jonasfj** [comment] 2020-08-04 09:22
Duplicate of https://github.com/dart-lang/pub-dev/issues/3834, please upvote in https://github.com/dart-lang/pub-dev/issues/3834 :D

**Closed by jonasfj** 2020-08-04 09:22 UTC
