### ISSUE TITLE
[Feature Request] Add support to GitHub's markdown

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/pub-dev#6475] opened 2023-03-06 16:34 UTC
I'm the author of this package: https://pub.dev/packages/eva

In GitHub, we can use the [https://mermaid.js.org/](https://mermaid.js.org/) to build some nice charts, just like this one:

```mermaid
stateDiagram-v2
    [*] --> Still
    Still --> [*]
    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]
```

(source: [https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/))

So, my README.md contains such a chart, but it doesn't work in the pub.dev website:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/379339/223172314-d82e82d9-2575-4b25-b4a3-d31ee6f71346.png">

So my suggestion is to add support for Mermaid.js, because it is a really useful framework for development documentation.

**Comment by sigurdm** [comment] 2023-03-07 11:11
Closing as duplicate of: https://github.com/dart-lang/pub-dev/issues/5763

**Closed by sigurdm** 2023-03-07 11:11 UTC
