### ISSUE TITLE
Tag null-safe packages and highlight this on package page

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3354] opened 2020-02-20 14:48 UTC
Exact Dart version that will be the lower bound is still TBD.

**Comment by jonasfj** [comment] 2020-02-20 14:49
Tag will probably be `is:null-safe` shown in UI as `Supports Null-Safety`.

**Comment by mit-mit** [comment] 2020-02-20 14:51
We should mark a package as null safe if, and only if, it satisfies all these properties (these assume we use 2.10 as the Dart versioning in which null safety is launched to stable):

  1. The SDK lower constraint is at least 2.10
  1. All direct dependencies of the package have a SDK lower constraint that is at least 2.10
  1. All indirect dependencies of the package have a SDK lower constraint that is at least 2.10

**Comment by mit-mit** [comment] 2020-09-02 15:27
Punting to beta 2.

**Comment by isoos** [comment] 2020-10-20 14:03
Duplicate of #4163. Keeping the newer one as it has a screenshot :)

**Closed by isoos** 2020-10-20 14:03 UTC
Labels: P1 high, Type: enhancement
