### ISSUE TITLE
Add a colon in the title of a package, so it is easier to copy and paste to an existing project

### ISSUE THREAD

**Issue by jorgecoca** [dart-lang/pub-dev#3968] opened 2020-08-26 18:18 UTC
Hello! 👋 

I see myself very often navigating pub.dev to find a package and its latest version. Every time I land on the package that I want, I tend to copy its title and version, and then go straight to my pubspec.yaml file to paste, and then I have to get in the middle of the string to add the colon necessary for yaml to parse the package and version... 

I think it might save some time and frustration to add a colon between the package name and its version, so it is a faster process. See screenshot below 👇 

![Screen Shot 2020-08-26 at 1 14 17 PM](https://user-images.githubusercontent.com/3237451/91340826-41064380-e79e-11ea-9d2e-bb2e834dca2d.png)

If you think this change request is worth it, I'd love to open a pull request including this! Let me know what you think!

Thank you!

**Comment by TimWhiting** [comment] 2020-08-26 18:58
Or even just put an invisible text element on top with the colon in it? Is that possible?

**Comment by pedromassango** [comment] 2020-08-26 19:52
I would like to suggest a small copy button for this feature request, so that we can just do a one click to copy instead of Double click or select by holding the mouse button.

**Comment by isoos** [comment] 2020-08-26 20:01
Thanks for filing the issue! I'm closing this, as the duplicate of #3336. We are planning to implement one of the suggested methods.

**Closed by isoos** 2020-08-26 20:01 UTC
