### ISSUE TITLE
Add keywords field to pubspec.yaml

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dev#368] opened 2017-09-20 04:37 UTC
_From @anders-sandholm on August 11, 2017 13:56_

_From @mnordine on August 11, 2017 12:59_

Search results on https://pub.dartlang.org/ could be improved with the addition of keywords for packages. It could also improve the home page by listing packages via popular keywords. For prior art, see https://crates.io/ and http://doc.crates.io/manifest.html

From the previous link:
```toml
# This is a list of up to five keywords that describe this crate. Keywords
# are searchable on crates.io, and you may choose any words that would
# help someone find this crate.v
keywords = ["...", "..."]
```

_Copied from original issue: dart-lang/sdk#30418_

_Copied from original issue: dart-lang/pub#1686_

**Comment by isoos** [comment] 2017-09-22 16:37
We already index description and the first part of readme. I'm not sure what another free-form text field could add to this, unless we want to promote these keywords somehow else. Thoughts?

**Comment by Ali-Azmoud** [comment] 2019-04-16 13:17
> We already index description and the first part of readme.  

No you don't. for example, you can't find [Flutter Xlider](https://pub.dartlang.org/packages/flutter_xlider) by keywords `xlider`, flutter xlider`, `(Flutter Xlider)` on google, while these words are inside the first part of readme. description as well

**Comment by isoos** [comment] 2019-04-16 14:14
@Ali-Azmoud: When I was say we index description and the first part of the readme, I was referring to the pub site. The pub site searches for [xlider](https://pub.dartlang.org/flutter/packages?q=xlider) and [flutter xlider](https://pub.dartlang.org/flutter/packages?q=flutter+xlider) bring up the package as the first hit. 

We also do expose lots of metadata for Google search to index the site, but we don't have direct influence on when, how and with what relevance it will happen.

**Comment by mit-mit** [comment] 2022-03-08 13:06
Closing as a duplicate of https://github.com/dart-lang/pub-dev/issues/5219 (that uses a slightly different mechanism for specifying the tags, but logically it's similar).

**Closed by mit-mit** 2022-03-08 13:06 UTC
Labels: Type: enhancement, Area: metadata needed
