### ISSUE TITLE
I would like to be able to "thumbs up" packages

### ISSUE THREAD

**Issue by dragonfax** [dart-lang/pub-dev#798] opened 2017-12-15 02:56 UTC
URL: https://pub.dartlang.org/

To show my support for the package. To show that I like something thats provided. To show that this package is used by someone. 

Or perhaps show the count of stars on the github repo for the package.

**Comment by isoos** [comment] 2017-12-15 09:45
If you are using it, that use will be reflected in the popularity score, and it provides a much better signal than the web-based voting, let it be github star or other means. ("Look at what they do, and not what they say.")

Considering all the other priorities, I don't think this will be implemented in the near future. 

I've reached out to a couple of package maintainers letting them know that I like what they did. It provides a rich feedback for the author, and it could also lead to conversations about what should be done next, which is another great value. I'd encourage that over anything else.

**Comment by mit-mit** [comment] 2019-10-09 15:41
#1517 was closed as a duplicate of the present issue

**Comment by isoos** [comment] 2019-12-11 07:55
This was done and deployed.

**Closed by isoos** 2019-12-11 07:55 UTC
Labels: Type: enhancement
