### ISSUE TITLE
How to develop a closed source flutter plugin?

### ISSUE THREAD

**Issue by Vishnupriya-M** [dart-lang/pub-dev#4532] opened 2021-02-19 12:40 UTC
Hi ,
We have developed a flutter plugin and we dont want to share the source code with the customer. When we run pub get it is possible to see the source code of each plugin that we added in pub cache. Is there any way to make it in binary file format or something like that?  Or is there any way to deliver a plugin with closed source code?
Please help me to get a solution for this.

Thank you .

**Comment by sigurdm** [comment] 2021-02-23 09:22
I don't think we have any way to support closed source plugins.

There is no stable official "bytecode" format for dart (there is the "kernel"-format) but that is not stable.

Once we had a dart2dart minifier that would obfuscate names in dart code. But I think that was removed from the sdk.

**Comment by Vishnupriya-M** [comment] 2021-02-23 09:41
Ok. Is it possible to build .aar for flutter plugin? I  copied the folders from flutter plugin and tried to make a flutter module and  build .aar. But i didnt get any single projectname .aar  file (as I expected) instead it generated multiple aars inside a repo folder with different names(including the names of plugins that I used in my plugin). Is it the right way to generate an .aar ? 
Thank you.

**Comment by sigurdm** [comment] 2021-02-23 10:45
I don't think there is away to do that.

This is not really a pub-dev issue. Closing as a duplicate of https://github.com/dart-lang/sdk/issues/43706 .

**Closed by sigurdm** 2021-02-23 10:45 UTC
