### ISSUE TITLE
API documentation issue in pub and locally the API doc generating properly

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [dart-lang/pub-dev#4779] opened 2021-05-07 08:12 UTC
API documentation is not generated for the below packages on the pub.

1. [syncfusion_flutter_pdf](https://pub.dev/packages/syncfusion_flutter_pdf/score)
2. [syncfusion_localizations](https://pub.dev/packages/syncfusion_localizations/score)

The below exception is thrown on the pub site.

```dart
exitCode: 255
stdout: Documenting syncfusion_flutter_pdf...
Initialized dartdoc with 316 libraries in 76.1 seconds
Generating docs for library pdf from package:syncfusion_flutter_pdf/pdf.dart...
stderr: Unhandled exception:
Assertion failed: "Reached 10485760 bytes in the output directory."
#0      PubResourceProvider._aboutToWriteBytes (package:pub_dartdoc/src/pub_hooks.dart:68:7)
#1      _File.writeAsBytesSync (package:pub_dartdoc/src/pub_hooks.dart:176:15)
#2      _File.writeAsStringSync (package:pub_dartdoc/src/pub_hooks.dart:182:5)
#3      DartdocFileWriter.write (package:dartdoc/dartdoc.dart:82:12)
#4      DartdocGeneratorBackend.write (package:dartdoc/src/generator/dartdoc_generator_backend.dart:103:12)
#5      DartdocGeneratorBackend.generateClass (package:dartdoc/src/generator/dartdoc_generator_backend.dart:162:5)
#6      GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:59:29)
#7      GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#8      Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:189:23)
<asynchronous suspension>
#9      Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:217:28)
<asynchronous suspension>
#10     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:34:19)
<asynchronous suspension>
```

But when we generate API docs locally it's generated properly.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/19346074/117418968-ab7c9f80-af39-11eb-9b5e-fac688f36477.png)

Can you guys please help me to get rid of this issue?

Thanks, Dharani.

**Comment by isoos** [comment] 2021-05-07 19:41
Duplicate of #4778.

**Closed by isoos** 2021-05-07 19:41 UTC
