### ISSUE TITLE
Unable to Setup `pub-dev` project on my local system using Fake Server

### ISSUE THREAD

**Issue by AmanNegi** [dart-lang/pub-dev#6375] opened 2023-01-27 11:04 UTC
## Issue
I am following [this](https://github.com/dart-lang/pub-dev/blob/master/doc/development.md) documentation to set up `pub-dev` on my Local System. Firstly, I installed dart and executed `dart pub get` to get all the packages. Then as mentioned in the documentation, I am trying to create a Fake Server using the following command:

> dart bin/fake_server.dart init-data-file --test-profile=test.yaml --analysis=fake --data-file=dev-data-file.jsonl

This returns me an error, which is basically a PathNotFound Error, the Logs are: 
- [Ubuntu 20.0.2](https://pastebin.com/BSqxV4NZ)
- [Windows 10](https://pastebin.com/6eK6DsFT)

## Things I tried
- As suggested by @isoos, I tried using `mono_repo` to run `dart pub get` recursively on all the folders.
- I tried using `dart pub cache` commands like `clear, add, repair`.
- Running on Administrator CMD also returns the same error.
- Executing the tests also returns errors.

I am a newbie and I may be missing something, so please help me with this issue.

**Comment by isoos** [comment] 2023-01-30 09:39
I think the root cause may be a change from 2.18 to 2.19 Dart SDK. At least I've found at least one issue that may be related to the error message you've seen as I'm upgrading the project in #6379.

**Comment by isoos** [comment] 2023-01-31 16:16
@AmanNegi: The upgrade PR landed. Could you please check with the latest HEAD + 2.19 SDK?

**Comment by AmanNegi** [comment] 2023-01-31 16:25
@isoos Yes it is working, now the recent PR seems to fix it!

**Comment by AmanNegi** [comment] 2023-02-01 02:21
@isoos: The `jsonl` file was successfully generated, however, the dart compiler is unable to find the file. After the file is generated I am trying to start the server using the following command:
> `dart bin/fake_server.dart run --data-file=dev-data-file.jsonl`

Complete [StackTrace](https://pastebin.com/dEY1Bzcr) of the error.

**Comment by isoos** [comment] 2023-02-01 07:57
Ah, `/bin/sh build.sh`. We have a few bash scripts that setup and/or build parts of the system. I don't think we will rewrite them for windows, they should be linux-only for the time being. I shall update the developer documentation about this limitation.

**Comment by AmanNegi** [comment] 2023-02-01 08:49
Okay thanks! I will do it on Ubuntu. Should I make those changes to the documentation.

**Closed** 2023-02-02 09:04 UTC
