### ISSUE TITLE
Package popularity is showing wrong (please do not report individual packages)

### ISSUE THREAD

**Issue by the-airbender** [dart-lang/pub-dev#7170] opened 2023-11-08 04:32 UTC
Hello!

My package popularity was 96% yesterday, it is showing as 0% now in pub dev. 
package: [quill_html_editor](https://pub.dev/packages/quill_html_editor)

I have observed this same issue for several other packages as well. 

Thanks & Regards,
Pavan

**Comment by tsinis** [comment] 2023-11-08 06:48
About 90% of packages in the pub.dev have been affected since yesterday night.

**Comment by isoos** [comment] 2023-11-08 06:50
@the-airbender @tsinis: Thanks for reporting! We are aware of the the issue: a backend rollup process that is part of the pipeline to get the popularity data out there is failing, somewhat inexplicably. We are working on fixing it, thanks for your patience!

**Comment by Jamalianpour** [comment] 2023-11-09 09:29
My packages has same issue

**Comment by tanzhongcheng** [comment] 2023-11-09 09:51
same issue

**Comment by temeddix** [comment] 2023-11-09 10:59
Same here

**Comment by benjith-kizhisseri** [comment] 2023-11-09 11:52
Same here

**Comment by abiodundotdev** [comment] 2023-11-09 12:45
same here

**Comment by anasfik** [comment] 2023-11-09 15:34
Hello, Thank you for your work first!

Is this data lost, or it will be recovered? can we have some info about it?

**Comment by isoos** [comment] 2023-11-09 15:54
> Is this data lost, or it will be recovered? can we have some info about it?

No data is lost, the popularity data will be recovered.

The issue is on the log-processing side (unrelated to site data), with a single, huge, dynamically built aggregation query that is run on the logs, doing way too many things inside the query / subqueries. This query is timing out (at 6 hours), probably because both the amount of traffic on the site increased and the dynamic parts got too large. The hard part is fixing the query without losing much of the features (e.g. bot detection), while the turnaround time makes very little room for iterating on it.

**Comment by mohanajuhi166** [comment] 2023-11-09 18:46
Same : My package was 80% but now showing 0%
https://pub.dev/packages/aad_b2c_webview

**Comment by Rexios80** [comment] 2023-11-11 22:01
If anyone is concerned about lost data, I have a website to track historical data for all packages here: https://pubstats.dev

**Comment by 41y08h** [comment] 2023-11-11 23:46
thought [this](https://stackoverflow.com/questions/65968434/how-popularity-percent-number-works-in-pubdev) is the answer for my package's popularity drop

**Comment by linglingier** [comment] 2023-11-12 12:49
安装不上提示，Connection terminated during handshake

**Comment by MohamedSalama0** [comment] 2023-11-12 17:18
same here in google_maps_flutter

**Comment by isoos** [comment] 2023-11-13 12:55
@shirvanie: please don't mix issues here. Open a new issue and file a verbose, including much more details and if possible the output of `dart pub publish -v`.

**Comment by aivantuquero** [comment] 2023-11-13 15:00
I noticed the same thing with getwidget, it was about 90+ popularity the other day.

**Comment by mokaily** [comment] 2023-11-14 12:59
same here

**Comment by Rexios80** [comment] 2023-11-14 17:40
@ivofernandes There are already discussions about that topic here: https://github.com/dart-lang/pub-dev/issues/2714 and https://github.com/dart-lang/pub-dev/issues/4732

**Comment by alexeyinkin** [comment] 2023-11-16 05:33
Meanwhile, is it possible to recover and show the last valid popularity values?

I think the more reliable approach would be to only overwrite the popularity if the script succeeded. If this is implemented, the recovered data will not be overwritten with zeros again.

I am applying for an official program for which I need to prove I made popular packages. Showing pub.dev to them is way easier than explaining what https://pubstats.dev is, how it works and why it can be trusted. (Thank you @Rexios80, super-cool!)

**Comment by quetool** [comment] 2023-11-16 12:51
Hello, this seems to be not just a popularity score issue. Also:

- UNKNOW PLATFORM it's shown although our packages supports Android and iOS.
- pub points it's stuck on pending status

Here you can see a version released yesterday vs a version released today:

<img src="https://github.com/dart-lang/pub-dev/assets/14978705/e2430ec6-2fb1-4e46-9648-e4410aacbe94" width="350">

<img src="https://github.com/dart-lang/pub-dev/assets/14978705/abda7046-c321-432e-a331-5b410d2344b0" width="350">

**Comment by Rexios80** [comment] 2023-11-16 13:12
If there isn't an easy way to recover the last values (and that's something you want to pursue) I could send you a dump from the https://pubstats.dev database

**Comment by isoos** [comment] 2023-11-16 15:36
@quetool: there is an ongoing release to update the analysis SDKs, it takes a bit time (up to a day) to analyze all packages. Usually we have a fallback analysis from the previous SDKs, but your package has a recently published version which was not analyzed with the previous SDKs either (we are using the same pool of workers and it gets busy around new analysis SDK release). Please be patient, it will get analyzed.

Re: label: until we haven't run the analysis, we can't really say much about the platforms, can we? We could assume it is the same as a version close by to it, but it could be also different, hence the "Unknown platforms" label - we just don't know.

**Comment by quetool** [comment] 2023-11-16 16:51
Thanks @isoos! I really appreciate the detailed answer! 🫡

**Comment by nggepe** [comment] 2023-11-18 11:39
Hello I think this issue is already resolved. My package popularity is back to normal, and I saw all the reported packages is back to normal.

<img width="839" alt="Screenshot 2023-11-18 at 18 37 59" src="https://github.com/dart-lang/pub-dev/assets/20833635/d6de2936-2ca9-4b57-a314-95ba503379ba">

**Comment by isoos** [comment] 2023-11-20 10:04
Closing the issue as the background process seems to be fixed now, and the site receives regular updates with the recent popularity data. Thank you all for being patient about this.

**Closed by isoos** 2023-11-20 10:04 UTC
Labels: Type: bug
