### ISSUE TITLE
No supported platform detected, and issue with null safety

### ISSUE THREAD

**Issue by MohammedAsaadAsaad** [dart-lang/pub-dev#4843] opened 2021-05-30 16:52 UTC
Hello, 
I published a new package to pub.dev, 
https://pub.dev/packages/quds_interactive

It scored 90/130, with two issues,
<b>First one:</b>
It says that no platform is supported and marked the package as `[UNIDENTIFIED]`

```
0/20 points: Supports 0 of 3 possible platforms (iOS, Android, Web)
Found 3 issues. Showing the first 2:

Consider supporting multiple platforms:

Package does not support Flutter platform Android
Because:

package:quds_interactive/quds_interactive.dart that imports:
package:quds_provider/quds_provider.dart that imports:
package:quds_provider/_src/src.dart that imports:
package:shared_preferences/shared_preferences.dart that imports:
package:shared_preferences_windows/shared_preferences_windows.dart that declares support for platforms: Windows
```
The used version of <b>shared_preferences</b> is <b>2.0.5</b> which supports all platforms.

<b>Second Issue</b>
```
Support sound null safety 0/20

0/20 points: Null safety support has one or more issues.
Tag detection failed.
Broken import package:/quds_interactive.dart

For more information
Try running dart pub outdated --mode=null-safety. Be sure to read the migration guide.
```

And I executed the mentioned command `dart pub outdated --mode=null-safety`,
and the result was that all dependencies support null safety
```
Resolving...
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Computing null safety support...
All your dependencies declare support for null-safety.
```
So what is the problem here?

**Comment by isoos** [comment] 2021-05-31 11:13
For the no tag part: one item jumps out: in `lib/quds_translation/pre_translated/pre_translated.dart` there is an `import '../../../quds_interactive.dart';`. However, if I count the `..` correctly, that points outside of the `lib/` directory.

**Comment by isoos** [comment] 2021-07-19 17:11
The no tag part was addressed in https://github.com/dart-lang/pana/pull/922 - which will provide more details when the analysis happens.
The first part is a duplicate of https://github.com/dart-lang/pana/issues/814

**Closed by isoos** 2021-07-19 17:11 UTC
