### ISSUE TITLE
task backend should not analyze packages not supported by Dart 2.12 or later

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#7622] opened 2024-04-09 13:17 UTC
Example:
https://pub.dev/packages/googleclouddatastore/pubspec

No analysis should be attempted for this package.

**Comment by jonasfj** [comment] 2024-04-09 13:19
Maybe what I mean is packages with an SDK bound of 2.11 or less should not be analyzed.

Since Dart 3.x SDKs can't analyze them.

**Comment by sigurdm** [comment] 2024-04-09 14:20
I agree with @isoos that even partial analysis can be useful - even if `dart analyze` will fail.

> https://pub.dev/packages/googleclouddatastore/pubspec

That package has a bogus `pubspec.yaml` (using '-' in a dependency-name) and should never have been uploaded. The problem is not really about the language version.

We should probably find ways to either mark such bogus packages, or ignore certain outputs from their analysis.

**Comment by isoos** [comment] 2024-05-01 06:55
`allDependencies` is now fixed in pana (does not emit bogus package names).

**Closed by isoos** 2024-05-01 06:55 UTC
Labels: Type: bug
