### ISSUE TITLE
Tagging of null-safety compliant packages on pub.dev

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3503] opened 2020-04-07 10:22 UTC
A package is said to null-safety compliant if:
 * The package has opted-in by specifying a lower dart sdk bound `>= 2.10`
 * No libraries in the package opts out of the null-safety enabled language version.
 * All (non-dev) dependencies in the latest version resolvable by `pub` are fully null-safety-compliant by this definition.

This needs to be implemented in `pana` and surfaced on `pub.dev`. I propose we tag such packages `is:null-safe` (which we can then use as a search filter).

On the package page null-safety will be displayed with an icon or other cool gadget to be determined.

**Comment by sigurdm** [comment] 2020-04-23 07:32
Pana now does the analysis for tagging packages: https://github.com/dart-lang/pana/commit/e38880387f4a9e56e72d7cd1d27b3b13d2116107

**Comment by isoos** [comment] 2020-06-17 12:22
Duplicate of #3354

**Closed by isoos** 2020-06-17 12:22 UTC
