### ISSUE TITLE
I cannot navigate to the 2nd page of Flutter Favorites

### ISSUE THREAD

**Issue by necatisozer** [dart-lang/pub-dev#3420] opened 2020-03-10 07:05 UTC
URL: https://pub.dev/flutter/favorites

When I press 2nd page or sorting options, it navigates to https://pub.dev/packages?page=2

**Comment by isoos** [comment] 2020-03-10 07:25
@necatisozer thanks for reporting! The fix was done in the code, we are in the process of deploying the new version that has it. (duplicate of #3401)

**Closed by isoos** 2020-03-10 07:25 UTC
