### ISSUE TITLE
The word "record" triggers issues in pubdev searches.

### ISSUE THREAD

**Issue by mi6ock** [dart-lang/pub-dev#7629] opened 2024-04-10 02:39 UTC
The word "record" triggers issues in pubdev searches.

![image](https://github.com/dart-lang/pub-dev/assets/12440462/ca9c80d7-5604-476d-9d3d-5661be9ffb65)

**Comment by amadzarak** [comment] 2024-04-10 02:52
It's the search functionality in general

**Comment by jonasfj** [comment] 2024-04-10 03:16
Thanks for reporting this!

Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/7624

**Closed by jonasfj** 2024-04-10 03:16 UTC
