### ISSUE TITLE
Google logo on pub.dev is blurry

### ISSUE THREAD

**Issue by cbenhagen** [dart-lang/pub-dev#6079] opened 2022-09-26 10:26 UTC
Very low prio issue, but wouldn't it be nice if the Google logo would have a higher resolution?

<img width="485" alt="Screen Shot 2022-09-26 at 12 21 47" src="https://user-images.githubusercontent.com/814785/192253955-52d1a6b6-26bc-4a46-b2cc-2a6cec40b1ad.png">

**Comment by isoos** [comment] 2022-09-26 11:25
Closing as this is a duplicate of #5760.

**Closed by isoos** 2022-09-26 11:25 UTC
