### ISSUE TITLE
rate limit has been reached

### ISSUE THREAD

**Issue by didiabel** [dart-lang/pub-dev#7595] opened 2024-03-26 17:00 UTC
The "package-published" operation is blocked, as its rate limit has been reached (3 in the last few minutes). Please try again later. Please report the issue on https://github.com/dart-lang/pub-dev/issues/new if you think the limit should be increased to accommodate your use case.

Please increase the rate limit.

**Comment by isoos** [comment] 2024-03-26 17:19
@didiabel: is there any specific reason why the limit should be increased? We think that package publishing should not happen too often, e.g. if you have 3 in two minutes, that seems to be a bit redundant, wasn't it?

**Comment by didiabel** [comment] 2024-03-26 17:29
hey @isoos , I already waited 1 hour and I still get the same error.

in the course of 4hs i only uploaded 6 times, and now have to wait a long time to be able to publish again. 

if we keep this rate limit then at least it should work as expected, maybe with a 10 or 30 minute cooldown.
dont you think?

![Screenshot 2024-03-26 at 2 26 15 PM](https://github.com/dart-lang/pub-dev/assets/66227018/e6a6b144-2a0d-47eb-a2a3-07470cbd89c9)

**Comment by isoos** [comment] 2024-03-26 18:08
Ah, this is a known issues (sorry for that it causes a bit confusion) which we haven't had time to debug yet. You have probably hit the daily publish limit, but the error message refers to the burst limit. Closing this issue, as it is the duplicate of #7522.

**Closed by isoos** 2024-03-26 18:08 UTC

**Comment by didiabel** [comment] 2024-03-26 18:10
ahh ok, whats the daily publish limit?. so i can adjust to it...

**Comment by isoos** [comment] 2024-03-26 18:37
12/day. However, the goal is not to max out this limit, you won't gain much benefit doing so. Your package seems to be new, without much use yet. I'd suggest to focus on improving it in larger batches, e.g. a readme and then an example update may not be that important to be published separately in this stage.
