### ISSUE TITLE
Hyperlinks are broken in API docs but work in pub.dev

### ISSUE THREAD

**Issue by osaxma** [dart-lang/pub-dev#6068] opened 2022-09-06 19:56 UTC
- All the hyperlinks shown in this page are broken (i.e. 404 error) when visiting the API docs at
  - https://pub.dev/documentation/analysis_server_client/latest/
<img width="682" alt="Screen Shot 2022-09-06 at 10 54 26 PM" src="https://user-images.githubusercontent.com/46427323/188726550-ea486b4a-841a-4601-8f21-d233e23acd50.png">

- The hyperlinks works fine at:
  - https://pub.dev/packages/analysis_server_client

Sorry if this is not the right repo. Please advise if this needs to be filed elsewhere.

**Comment by sigurdm** [comment] 2022-09-22 08:39
We do something smart on the readme tab with linking to the github files. Perhaps we could do the same thing for the dartdoc... But that seems to be a band-aid.

Really we should have a better integration of dart-doc's rendering of the README, and dartdoc (or perhaps pub.dev) should have code listings such that we do not have to link to github.

**Comment by isoos** [comment] 2023-09-25 19:07
Closing this as duplicate of #3975.

**Closed by isoos** 2023-09-25 19:07 UTC
Labels: Type: bug
