### ISSUE TITLE
I wish there were a dark mode

### ISSUE THREAD

**Issue by widgetizer** [dart-lang/pub-dev#7729] opened 2024-05-15 01:53 UTC
URL: https://pub.dev/

I'd love it if pub.dev had a dark mode. I tell myself it eases eye strain, but it really just makes me feel like Batman.

**Comment by isoos** [comment] 2024-05-15 07:34
Closing as duplicate of #4416. Please upvote the existing issue.

**Closed by isoos** 2024-05-15 07:34 UTC
