### ISSUE TITLE
Allow customization of the "install" tab

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3403] opened 2020-03-03 14:58 UTC
We should render `INSTALL.md` on the "install" tab, if the package contains an `INSTALL.md` file.
(motivated by https://github.com/dart-lang/pub-dev/issues/2125)

This allows packages with external dependencies to specify how they are installed. Imagine packages using `dart:ffi`, it also allows packages that can be globally activated to indicate that this is how they should be used. And it allows packages that prefers to be `dev_dependencies` to indicate this.

Moreover, it allows packages to recommend version constraint ranges, useful in cases when bump to `1.0.0` happened for cosmetic reasons and didn't cause any breaking changes (#3385).

Mostly, I think this is generally useful to allow packages to specify their own install instructions, if they want to.

@mit-mit, @kevmoo, thougths?

**Comment by kevmoo** [comment] 2020-03-03 16:16
Not a bad idea!

I pondered if we should have a field or fields in the pubspec for this. But maybe just an MD file is better.

**Comment by jonasfj** [comment] 2020-03-10 09:50
@sigurdm suggest we could also remove the install tab.

**Comment by elbeicktalat** [comment] 2021-04-16 09:01
Great it's very helpful 👌

**Comment by leighajarett** [comment] 2022-09-22 00:07
+1 This came up in product research sessions at Flutter Vikings. A few developers mentioned that they wanted control over the install tab. Specifically they wanted to be able to mention other setup steps that are required. Right now this tends to fall in the "Getting Started" tab but developers seemed to think that should be reserved for actually beginning to write code.

**Comment by sigurdm** [comment] 2022-09-22 07:55
I think custom information in the install tab would easily go unnoticed.

How would someone know to look there if most packages have the default instructions?

**Comment by anderdobo** [comment] 2023-06-14 15:50
+1 this has come up as we assess documentation quality of Flutter Favorite candidates. We find that packages that are meant to be dev dependencies have a discrepancy between their README(e.g. https://pub.dev/packages/flutter_flavorizr) which instructs to manually add under dev_dependencies in pubspec.yaml, and the instructions on the "Install" tab (e.g. https://pub.dev/packages/flutter_flavorizr/install of the package, which provides a command that adds as a regular dependency. It would be useful to provide package authors with a mechanism that makes the instructions on the "Install" tab relevant for a dev dependency (e.g. provide the command `dart pub add [package_name] --dev`)

**Comment by mit-mit** [comment] 2023-06-15 09:45
Yeah, I think this is a great idea too!

**Comment by sigurdm** [comment] 2023-06-15 09:45
@anderdobo 

> We find that packages that are meant to be dev dependencies have a discrepancy between their README , and the instructions on the "Install" tab

I think we should address this by making it possible to mark a package specifically for being a dev-dependency: see https://github.com/dart-lang/pub-dev/issues/6400

**Comment by stuartmorgan** [comment] 2024-01-24 20:46
Should this be merged with https://github.com/dart-lang/pub-dev/issues/3403 ? I was trying to find this issue again today and found both; it seems like they are tracking the same thing.

**Comment by sigurdm** [comment] 2024-01-25 09:08
Closing this as duplicate of https://github.com/dart-lang/pub-dev/issues/2967

**Closed by sigurdm** 2024-01-25 09:08 UTC
Labels: Type: enhancement
