### ISSUE TITLE
Please add a quick action to install the latest version of a package

### ISSUE THREAD

**Issue by lukas-h** [dart-lang/pub-dev#3902] opened 2020-08-02 22:51 UTC
It's fairly difficult if you just want to grab the code to install the latest version of a package.
You have to navigate to "Installing" and then manually select and copy the version you want to use.

It could look like this:

<img width="257" alt="example pub.dev" src="https://user-images.githubusercontent.com/10634693/89134125-9befa680-d522-11ea-8642-69b8d85d37ca.png">

(This was placed in the sidebar of a package page pub.dev/packages/PACKAGE_NAME)

rubygems.org or npm have similar shortcuts.

**Comment by isoos** [comment] 2020-08-04 08:56
@lukas-h: thanks for the suggestions. I'm closing this, as this is the duplicate of #3336. Could you upload the image mock there too?

**Closed by isoos** 2020-08-04 08:56 UTC
