### ISSUE TITLE
Expose API for listing all package names

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4092] opened 2020-10-06 09:32 UTC
`GET pub.dev/api/package-names`

TODO: investigate if we could use the API end-point `pub.dev/api/packages/`, and remove the existing API from there (need to look at logs).

-----------------

Also document this in something like `doc/api.md`.

**Comment by isoos** [comment] 2020-11-27 12:12
Duplicate of #4282.

**Closed by isoos** 2020-11-27 12:12 UTC
Labels: Type: enhancement
