### ISSUE TITLE
Pub is not feeling well 

### ISSUE THREAD

**Issue by frankcheng2008** [dart-lang/pub-dev#4493] opened 2021-02-04 07:44 UTC
Pub is not feeling well 
Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dev/issues/new

Add these details to help us fix the issue:

Requested URL: https://pub.dev/packages/provider
Request ID: 88538196a7a11bf36aeb6dd29a72e38a

**Comment by jonasfj** [comment] 2021-02-04 12:12
Thanks for the report :+1: 

The issue should be resolved, closing as duplicate of https://github.com/dart-lang/pub-dev/issues/4485

**Closed by jonasfj** 2021-02-04 12:12 UTC
Labels: Resolution: duplicate
