### ISSUE TITLE
Admin UI for add/remove uploaders

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3553] opened 2020-04-22 20:06 UTC
We very rarely need admin API for adding/removing package uploaders and publisher members.
We currently do this using CLI tools, however, these have no testing and is broken from time to time.

**Comment by isoos** [comment] 2020-10-21 10:10
Duplicate of #3553, closing this one.

**Closed by isoos** 2020-10-21 10:10 UTC
Labels: P3 low
