### ISSUE TITLE
Googleapis docs have broken links

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#6678] opened 2023-05-22 11:01 UTC
See https://pub.dev/documentation/googleapis/latest/index.html

The links to the API details for all Google APIs are missing (404).

Not sure if the issue is with package:googleapis, dartdoc, or our integration.

**Comment by isoos** [comment] 2023-05-22 11:29
Closing this as a duplicate of #6594. Dartdoc seems to have changed the way they are generating some files, and fixed links in the readme are not updated. Not sure if the fix should go into dartdoc or in the readme.

**Closed by isoos** 2023-05-22 11:29 UTC
