### ISSUE TITLE
README.md image URLs are using 'master' instead of 'main' for repos using 'main'.

### ISSUE THREAD

**Issue by mcsocket** [dart-lang/pub-dev#5617] opened 2022-03-28 20:18 UTC
I noticed some broken image links in [our README](https://pub.dev/packages/capturesdk) and noticed that if I switched our `master` for `main` the link works. See the two links below.

Link that is currently in use but doesn't work: https://github.com/SocketMobile/capturesdk_flutter_snapshot/raw/master/runnerimg.png

Link that is not in use but does work:
https://github.com/SocketMobile/capturesdk_flutter_snapshot/raw/main/runnerimg.png

This might be a bug that is easily fixed. Wherever you generate the content links you should consider the name of the branch being used in the provided repo as the master/main one rather than assuming it will always be master (if that is the case currently). 

If there is something else that I can do to ensure `main` is used in the REAME content links rather than `master` I'd be happy to make the fix.

**Comment by isoos** [comment] 2022-03-29 11:21
We're working on a repository verification, which, among other things, will provide the default branch name, and that will be used to rewrite the URLs.

Closing as this is a duplicate of #5068.

**Closed by isoos** 2022-03-29 11:21 UTC
