### ISSUE TITLE
pub.dev not tagging packages that are null-safe with the null-safety tag

### ISSUE THREAD

**Issue by dshukertjr** [dart-lang/pub-dev#5061] opened 2021-08-28 06:19 UTC
Hi everyone! Thanks for maintaining such an amazing echo system! 

I have a question/request regarding the `null-safety` tag.  I'm finding that some packages that have migrated to null-safety does not seem to be getting `null-safety` tag shown in the image.

<img width="761" alt="Screen Shot 2021-08-28 at 15 11 01" src="https://user-images.githubusercontent.com/18113850/131208257-4db1aa4b-9831-4c06-8437-bd97b42c4d04.png">

Example of null-safe packages that don't have the tag are
- https://pub.dev/packages/supabase_flutter
- https://pub.dev/packages/hive_flutter

If we go to the `versions` tab, we can see that their newest version does use null-safety. 

What exactly are the qualification to receive the tag on the top page and could we have a clear description somewhere that outlines the qualification (sorry if I had missed it).

**Comment by isoos** [comment] 2021-08-28 07:40
@dshukertjr:

For the qualification (esp. the reason of rejection) visit the package's `Scores` tab, and open the `Support sound null safety` report section. You'll see in both cases that the reason they do not support it is a dependency violation from the automatic analysis: they may import `dart:indexed_db`, but that is not accessible (from Flutter SDK).
There is an open issue in Flutter for it: https://github.com/flutter/flutter/issues/44937

Closing this as duplicate of https://github.com/dart-lang/pana/issues/891

**Closed by isoos** 2021-08-28 07:40 UTC
