### ISSUE TITLE
Package documentation scoring

### ISSUE THREAD

**Issue by fredeil** [dart-lang/pub-dev#5285] opened 2021-11-22 11:55 UTC
My package https://pub.dev/packages/email_validator has recently received a 10/20 documentation score.

The reason being:
`0/10 points: 20% or more of the public API has dartdoc comments`

It states that to fix the issue: `Document at least 20% of the public API elements`.
In reality 100% of the public methods (only 1 public facing method) are documented in my case (rest are internal/private methods that are undocumented).

How is the statement relevant for my library/code?

See https://github.com/fredeil/email-validator.dart/blob/master/lib/email_validator.dart#L294

Screenshot: https://user-images.githubusercontent.com/17533404/142856592-9807dd6f-493c-4f63-85da-50b96f804402.png

**Comment by isoos** [comment] 2021-11-22 12:18
Thanks for reporting the issue. I'll mark this as a duplicate of #5194.

For your specific case, at first glance, you have multiple things in the API surface which we should mention in the report:
- a library (which may have a documentation)
- a public class with a public constructor (these may have separate documentation)
- a public enum (`type`) with 4 values + extra method, all without documentation.

If you were to limit your API surface, I think the wrapper class is not really useful (especially as the single public method is `static`), and the enum could be potentially be private too. 

One takeaway for the scoring is that if a package has a single library, we should not count that here, as it becomes important if you have multiple top-level libraries.

**Closed** 2021-11-25 10:06 UTC
Labels: Resolution: duplicate
