### ISSUE TITLE
The pub installing tab doesn't show dev_dependencies

### ISSUE THREAD

**Issue by feinstein** [dart-lang/pub-dev#2125] opened 2019-03-12 14:34 UTC
The installing instructions [here](https://pub.dartlang.org/packages/test#-installing-tab-) show:

```
dependencies:
  test: ^1.5.3
```

while it should be:

```
dev_dependencies:
  test: ^1.5.3
```

**Comment by natebosch** [comment] 2019-03-14 00:30
It would be handy to be able to indicate somewhere in the pubspec when a package is _usually_ a dev dependency.

**Comment by isoos** [comment] 2019-04-15 10:28
@jonasfj we could infer this from the pubspec.yaml files: if a package is 90%+ referenced only as part of the `dev_dependencies:`, we could display the different label. However, it should be probably part of the package dependency graph or search.

**Comment by jonasfj** [comment] 2019-04-15 10:33
We could also make a convention `install.md` is render there if present..

**Comment by isoos** [comment] 2019-04-15 10:36
`install.md` sounds good, and/or we could also extract it from readme (if we had the parsing and table-of-content extraction for it).

**Comment by devoncarew** [comment] 2020-03-02 16:47
Can we bump the priority of this issue? We're likely going to reference the installing page for package:test from tooling and docs, and it currently provides incorrect guidence.

https://pub.dev/packages/test#-installing-tab-

Even one-off handling pf package:test would be a useful workaround (if a general purpose solution isn't feasible in the near term).

**Comment by isoos** [comment] 2020-03-02 17:45
@devoncarew: I've submitted #3397 to simply change the `dependencies` to `dev_dependencies` in the case of `package:test`. Is there any other urgent part to be fixed?

**Comment by devoncarew** [comment] 2020-03-02 17:58
Nope, that's it; thanks!

**Comment by jonbhanson** [comment] 2021-05-21 19:42
Users of my package, [flutter_native_splash](https://pub.dev/packages/flutter_native_splash), have contacted me with confusion because my readme tells them to add a in `dev_dependencies` (with is correct), but the installing tab tells them to add in `dependencies` (which is incorrect).  Would be nice to get this fixed!

**Comment by sigurdm** [comment] 2023-03-30 08:41
Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/6400

**Closed by sigurdm** 2023-03-30 08:41 UTC
Labels: Type: enhancement
