### ISSUE TITLE
Image variant aware of dark/light theme.

### ISSUE THREAD

**Issue by HosamHasanRamadan** [dart-lang/pub-dev#6119] opened 2022-10-14 14:47 UTC
pub.dev doesn't show theme aware images that GitHub supports [info](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to).

- check my app GitHub page, [pub](https://pub.dev/packages/fshare) vs [GitHub](https://github.com/HosamHasanRamadan/fshare)

**Comment by isoos** [comment] 2022-10-24 06:54
Closing as duplicate of #5923.

**Closed by isoos** 2022-10-24 06:54 UTC
