### ISSUE TITLE
I cannot find 'angular_router'

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/pub-dev#2876] opened 2019-10-08 07:58 UTC
URL: https://pub.dev/web/packages?q=angular_router&page=2

... but the package obviously exists:
https://pub.dev/packages/angular_router
even for Dart 2, of course:

https://pub.dev/packages/angular_router/versions/2.0.0-alpha+24

**Comment by isoos** [comment] 2019-10-08 08:01
This is a duplicate of #2715, with the added complexity that you are filter in `/web/` packages. As `angular_router`'s latest stable is not Dart 2 compatible, and it is not analyzed, it is not classified as `web` package (and it does not rank high on the results page if you just search without the `web` filter).

**Closed** 2019-12-10 23:13 UTC
