### ISSUE TITLE
False-positive report with GitHub Issue tracker URL

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#7592] opened 2024-03-26 02:43 UTC
https://pub.dev/packages/dio_http2_adapter/score

<img width="853" alt="image" src="https://github.com/dart-lang/pub-dev/assets/15884415/8d880315-f878-463d-9560-bd5a3360c137">

**Comment by isoos** [comment] 2024-03-26 07:38
Closing as a duplicate of #7388.

**Closed by isoos** 2024-03-26 07:38 UTC
Labels: Type: bug
