### ISSUE TITLE
Spam Packages "Watch [xyz] movie Free Online" 

### ISSUE THREAD

**Issue by taoleaf** [dart-lang/pub-dev#4003] opened 2020-09-08 05:07 UTC
URL: https://pub.dev/packages/watch_after_we_collided_2020_full_hd_movie_online_free

Pub.dev is getting hit with a bunch of fake packages spamming pirated movies. Code Whiskey Tango Foxtrot

**Comment by isoos** [comment] 2020-09-08 07:52
Thanks for reporting. Closing as duplicate of #3993.

**Closed by isoos** 2020-09-08 07:52 UTC
