### ISSUE TITLE
Is there any way to change the name of package uploaded. 

### ISSUE THREAD

**Issue by jaiswalshubham84** [dart-lang/pub-dev#3789] opened 2020-07-07 15:28 UTC
Is there any way to change the name of the package uploaded. I was not intentionally publishing the package, but somehow it got published by mistake.

The package is not ready up to mark and the also naming is completely wrong.
Its just got uploaded accidently.

If the package can somehow be unpublished, it will be a great help.

package link: https://pub.dev/packages/launchexternalapp/

**Comment by isoos** [comment] 2020-07-08 20:33
Duplicate of https://github.com/dart-lang/pub-dev/issues/3788

**Closed by isoos** 2020-07-08 20:33 UTC
