### ISSUE TITLE
Can i go back to the previous design?

### ISSUE THREAD

**Issue by dmvvilela** [dart-lang/pub-dev#3852] opened 2020-07-17 19:35 UTC
URL: https://pub.dev/help

This new "elegant" design looks like i am shopping in a clothing store..

The design was already new, no need to change! Also reference API for a package was EVERYTHING BOLD! I hope this was a bug.. for real

**Comment by isoos** [comment] 2020-07-17 19:45
> Also reference API for a package was EVERYTHING BOLD! I hope this was a bug.. for real

@dmvvilela: could you please clarify what you see as all-bold?

**Comment by dmvvilela** [comment] 2020-07-17 19:51
Hmm i don't know what happened actually. This page: 
https://pub.dev/documentation/pdf/latest/pdf/PdfPage-class.html

Everything was bolder.. but now is ok so alright.. Still i don't understand the new design.. Doesn't look like it is for code.

**Comment by sigurdm** [comment] 2020-07-20 12:13
The new design is there to stay (until we redesign again...) and we will not be maintaining two different designs.

I'm afraid there is not much actionable we can do here - taste is hard to debate.

But please open issues for concrete problems with the new design.

**Comment by dmvvilela** [comment] 2020-07-20 13:27
Ok, you right.. Sorry.. So about the new design.. Where is the search bar?

I can only see it in the main page.. in a package page it's not there anymore, so i have to go to the main page to search for another package..  This is a usability feature, so is this something that i can ask here?

**Comment by isoos** [comment] 2020-07-20 13:32
@dmvvilela: yes, search bar is perfectly valid question. As it is a duplicate of another issue, could you please add your comment / answer the questions on this: https://github.com/dart-lang/pub-dev/issues/3860#issuecomment-661011420

I thought that the "Back to search" is visible to all, but apparently it is not, or it is being missed.

**Comment by sigurdm** [comment] 2020-07-20 13:37
Closing this issue for now.

Please open new issues for each trouble you find (or just +1 if they are already reported).

**Comment by febritecno** [comment] 2020-07-20 13:37
I strongly agree with the opinions on this issue. very comfortable web design before.

the back button often doesn't appear

![image](https://user-images.githubusercontent.com/9696688/87943851-cf651680-cac8-11ea-9c9c-81d1e18d291f.png)

**Closed** 2020-07-20 13:37 UTC

**Comment by dmvvilela** [comment] 2020-07-20 13:40
Ok, ill put it there..

Just one last comment, my problem is not the design per se.. but the font used! Too skinny.. The design by itself is pretty good!

And i really did not see a back to search button :/

**Comment by febritecno** [comment] 2020-07-20 13:44
@dmvvilela  
this problem is the same that I feel. it is too difficult to search for packages while on the package details page. hopefully it can be like before.
