### ISSUE TITLE
Please add Dark theme to pub.dev!

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/pub-dev#7533] opened 2024-03-06 01:36 UTC
It's extremely uncomfortable to use a light theme when using pub.dev, especially if you are using a dark mode in your OS, IDE, Terminal, GitHub and all other development tools.

IMHO, since it's a development site, the default theme should be dark.

**Comment by isoos** [comment] 2024-03-06 10:56
This is duplicate of #4416, closing for now.

**Closed by isoos** 2024-03-06 10:56 UTC
