### ISSUE TITLE
Error when accessing the site through direct link https://pub.dev/packages/flutter_audio_recorder

### ISSUE THREAD

**Issue by petrblahos** [dart-lang/pub-dev#4490] opened 2021-02-04 07:40 UTC
Hi, I am filing this issue because pub.dev site asked me to. Accessed the address https://pub.dev/packages/flutter_audio_recorder from google search results, and got:

Pub is not feeling well 
Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dev/issues/new

Add these details to help us fix the issue:

Requested URL: https://pub.dev/packages/flutter_audio_recorder
Request ID: 6f53b0da55ce7a77ab7f10452cea95aa

When retried in 1 minute it worked.

**Comment by jonasfj** [comment] 2021-02-04 12:11
Thanks for the report :+1: 

The issue should be resolved, closing as duplicate of https://github.com/dart-lang/pub-dev/issues/4485

**Closed by jonasfj** 2021-02-04 12:11 UTC
Labels: Resolution: duplicate
