### ISSUE TITLE
pub not feeling well!

### ISSUE THREAD

**Issue by beshoy220** [dart-lang/pub-dev#7626] opened 2024-04-10 02:01 UTC
i was just searching packages and the pub just did not work well.

```
Requested URL: https://pub.dev/packages?q=file+explore
Request ID: 747874ea15c4c268bc09521b1ae88a00
```

**Comment by jonasfj** [comment] 2024-04-10 03:16
Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/7624

**Closed by jonasfj** 2024-04-10 03:16 UTC
Labels: Resolution: duplicate
