### ISSUE TITLE
I'd like to suggest a test.pub.dev

### ISSUE THREAD

**Issue by winksaville** [dart-lang/pub-dev#3650] opened 2020-05-24 01:27 UTC
I published my first two packages and made some stupid mistakes. I'd like to suggest a test.pub.dev instance of pub.dev where by full round trip testing could be done prior to a "forever" upload to pub.dev.

For more information see [this discussion](https://gitter.im/dart-lang/TALK-general?at=5ebdfbddda74582e921d20db) on gitter.

**Comment by isoos** [comment] 2020-05-25 09:10
Direct link to the mistakes mentioned: https://gitter.im/dart-lang/TALK-general?at=5eca844ea91f120a6cbcf519

> Actually there was nothing wrong with the docs, the main problem was I hadn't changed the "homepage" field in the pubspec.yaml (and then didn't do the fix correctly, LoL) and had left in some debug. I do believe that a "test.pub.dev" site would have helped me, because the problem was caught when I tried to use use the web pages generated by pub.dev. Actually, "test.pub.dev" would be a "playground" and there should also be something like chromes "dev", "beta" and "stable" channels with only "stable" being forever.

**Comment by isoos** [comment] 2020-05-25 09:14
@jonasfj: This could be one of the features of the staged publishing, however, I think it would be better to provide these checks as part of the `pub publish --dry-run`. E.g. the `homepage` / `repository` URL rendering is something `pub` could emit - if we had the shared package between them.

**Comment by jonasfj** [comment] 2020-05-26 13:03
This seems very much aligned with the incomplete thoughts we have around _staged publishing_.

**Comment by winksaville** [comment] 2020-05-27 00:00
> This seems very much aligned with the incomplete thoughts we have around _staged publishing_.

I just took the survey and added added by desire to have that feature, I also mentioned the notion of having a test.pub.dev. I hope we see it in the future!

**Comment by sigurdm** [comment] 2023-02-16 10:19
Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/4489

**Closed by sigurdm** 2023-02-16 10:19 UTC
