### ISSUE TITLE
Need Dark Theme support in pub.dev

### ISSUE THREAD

**Issue by abinvs-2019** [dart-lang/pub-dev#6122] opened 2022-10-19 10:04 UTC
Need dark theme in pub.dev.

**Comment by abinvs-2019** [comment] 2022-10-19 10:07
I could do this if anyone could guide me.
Thank you.

**Comment by isoos** [comment] 2022-10-19 10:42
Closing as a duplicate of #4416. Please update existing issues when they exist. Note: we don't have an immediate plan or design for dark mode, but it is on our radar.

**Closed by isoos** 2022-10-19 10:42 UTC
