### ISSUE TITLE
Site doesn't maintain authentication state on mobile

### ISSUE THREAD

**Issue by mpfaff** [dart-lang/pub-dev#3164] opened 2019-12-12 03:43 UTC
The mobile version of pub.dev seems to either not maintain or not detect authentication state correctly. For example, I clicked the like button on a package, signed in with my Google account, and then although the like action worked, the menu bar still had the "sign in" button instead of the profile button

**Comment by isoos** [comment] 2019-12-18 20:21
@mpfaff: could you please share a bit more detail about the mobile os and browser you were using?

**Comment by mpfaff** [comment] 2019-12-18 22:07
I encountered this issue on Android 10 running Google Chrome 78.0.3904.108 (Chrome Stable) and 80.0.3987.9 (Chrome Dev)

**Comment by isoos** [comment] 2019-12-19 11:16
My Chrome 79 on Android 6 was not able to reproduce the issue. Do you have any extensions active (or anything that would intercept the authentication calls)?

**Comment by mpfaff** [comment] 2019-12-20 01:49
Not sure if you mean Chrome extensions or something else, but obviously I wouldn't have any on my phone. I've tested on Wifi and data, with my VPN on and off.

**Comment by isoos** [comment] 2020-05-19 07:38
Could not reproduce the issue, closing.

**Closed by isoos** 2020-05-19 07:38 UTC

**Comment by mpfaff** [comment] 2020-05-26 19:01
@isoos I totally forgot this issue was even open. Not sure if it was me, Chrome, or pub.dev, but the issue stopped happening months ago.
