### ISSUE TITLE
The installing page for package:test gives inaccurate guidance for use of the pubspec

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub-dev#3391] opened 2020-02-29 18:38 UTC
The installing page for package:test:

https://pub.dev/packages/test#-installing-tab-

gives inaccurate guidance for how to add support for it to the pubspec.yaml file. It says:

```
Add this to your package's pubspec.yaml file:

dependencies:
  test: ^1.12.0
```

It should instead recommend adding it to a (likely new to the user's pubspec) `dev_dependencies` section.

If recommending `dev_dependencies` in this page is hard to generalize, it would worth special casing `package:test`, given how widely used it is.

**Comment by isoos** [comment] 2020-03-02 07:09
@devoncarew Thanks for reporting that. Closing as it is duplicate of #2125.

**Closed by isoos** 2020-03-02 07:10 UTC
