### ISSUE TITLE
Fatal package site error.

### ISSUE THREAD

**Issue by ahmtcn123** [dart-lang/pub-dev#4488] opened 2021-02-04 07:37 UTC
I hope it helps

Requested URL: https://pub.dev/packages/ping_discover_network
Request ID: e90db1860b39ebe494d96c95f4f81399
![Screenshot_12](https://user-images.githubusercontent.com/26122392/106860236-23d28b00-66d5-11eb-9854-8ccbce324085.png)

**Comment by jonasfj** [comment] 2021-02-04 12:10
Thanks issue should be resolved, closing as duplicate of https://github.com/dart-lang/pub-dev/issues/4485

**Closed by jonasfj** 2021-02-04 12:10 UTC
Labels: Resolution: duplicate
