### ISSUE TITLE
Display a related list of packages

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#211] opened 2017-07-07 05:28 UTC
We could detect it from:
- the name, or
- the author, or
- the dependencies,
- pubspec entry

**Comment by orestesgaolin** [comment] 2020-09-23 08:17
Would love to have a way to reference similar packages by its name in the pubspec or website GUI. This could also be detected from the tags/keywords #368

**Comment by mit-mit** [comment] 2022-03-08 13:07
Closing as a duplicate of https://github.com/dart-lang/pub-dev/issues/5219. Please vote on that one instead.

**Closed** 2023-05-11 09:00 UTC
Labels: Type: enhancement, P3 low
