### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by abdallahboucedraya** [dart-lang/pub-dev#5349] opened 2021-12-13 08:36 UTC
URL: https://pub.dev/

Add notifications for packages to get a notice when the package has been updated.

**Comment by sigurdm** [comment] 2021-12-13 12:25
We are currently working on pub-dependabot integration! https://github.com/dependabot/dependabot-core/pull/4510 that should solve a lot of the use-cases for this.

But I agree some other kind of notification system would be neat.

**Comment by isoos** [comment] 2022-10-21 11:32
Closing as duplicate of #5532.

**Closed by isoos** 2022-10-21 11:32 UTC
Labels: Type: enhancement
