### ISSUE TITLE
Need a dark theme for the Site

### ISSUE THREAD

**Issue by bhaskar-nair2** [dart-lang/pub-dev#6359] opened 2023-01-22 11:42 UTC
URL: https://pub.dev

I really need a dark theme for the entire site. I am constantly flashbanged by the entire site.

**Comment by sigurdm** [comment] 2023-01-23 09:23
Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/4416

**Closed by sigurdm** 2023-01-23 09:23 UTC
