### ISSUE TITLE
Error: FormatException: Scheme not starting with alphabetic character (at character 1) (https:/github.com/Baseflow/flutter-permission-handler/blob/develop/example... 

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#7668] opened 2024-04-22 08:38 UTC
```
Error: FormatException: Scheme not starting with alphabetic character (at character 1) (https:/github.com/Baseflow/flutter-permission-handler/blob/develop/example... ^

at ._Uri._fail
at ._Uri._makeScheme
at ._Uri.notSimple
at .Uri.parse
at .pkgDocUrl ( package:pub_dev/shared/urls.dart:165 )
at .documentationHandler ( package:pub_dev/frontend/handlers/documentation.dart:54 )
at RouterEntry.invoke.<fn> ( package:shelf_router/src/router_entry.dart:109 )
at .RouterEntry.invoke ( package:shelf_router/src/router_entry.dart:104 )
at .Router.call ( package:shelf_router/src/router.dart:184 )
at createAppHandler.<fn> ( package:pub_dev/frontend/handlers.dart:74 )
at _redirectLoopDetectorWrapper.<fn> ( package:pub_dev/shared/handler_helpers.dart:93 )
at _cspHeaderWrapper.<fn> ( package:pub_dev/shared/handler_helpers.dart:147 )
at _userAuthWrapper.<fn>.<fn> ( package:pub_dev/shared/handler_helpers.dart:243 )
at .AccountBackend.withBearerToken ( package:pub_dev/account/backend.dart:287 )
at _userAuthWrapper.<fn> ( package:pub_dev/shared/handler_helpers.dart:242 )
at _requestContextWrapper.<fn> ( package:pub_dev/shared/handler_helpers.dart:135 )
at _httpsWrapper.<fn> ( package:pub_dev/shared/handler_helpers.dart:258 )
at _sanitizeRequestWrapper.<fn> ( package:pub_dev/shared/handler_helpers.dart:226 )
at _logRequestWrapper.<fn> ( package:pub_dev/shared/handler_helpers.dart:171 )
at .handleRequest ( package:shelf/shelf_io.dart:138 )
```

**Comment by isoos** [comment] 2024-04-22 08:56
Duplicate of #7662.

**Closed by isoos** 2024-04-22 08:56 UTC
