### ISSUE TITLE
Package `ansi` analysis pending over 4 days

### ISSUE THREAD

**Issue by hyiso** [dart-lang/pub-dev#6962] opened 2023-08-23 13:04 UTC
See the package page https://pub.dev/packages/ansi/score

The analysis process has been pending over 4 days

**Comment by isoos** [comment] 2023-08-23 14:26
@hyiso: thanks for reporting this.
@jonasfj: there is no task-log available for `ansi/0.3.0` could you please check if the `PackageState` was updated with anything?

**Comment by natsuk4ze** [comment] 2023-08-24 04:51
I think this is a duplicate of #6953

**Comment by jonasfj** [comment] 2023-08-24 09:29
Thanks for reporting this. It looks like out scanning loop failed temporarily and our overlap was probably too low. Essentially, it was meant to recover within 30 min or so, but since it missed that window it'll take 7 days.

We will look to fix the bug and increase our scanning loop... in the meantime I'll manually trigger an analysis run.

**Comment by isoos** [comment] 2023-08-24 09:45
Note: the trigger worked, it got analyzed.

**Comment by natsuk4ze** [comment] 2023-08-24 09:48
I am waiting for an analytics fix too for [my package](https://pub.dev/packages/gal). Is there anything I can do?

**Comment by jonasfj** [comment] 2023-08-25 08:26
@natsuk4ze looks like it just got picked up organically :D

Hmm, I'm still not sure why it took so long to get picked up. Maybe there was a problem with the scanning loop, and hopefully https://github.com/dart-lang/pub-dev/pull/6965 will fix that.
```
"2023-08-25T05:50:02.343688571Z": pub.task.backend: Update state tracking for gal
```

**Closed by jonasfj** 2023-08-25 08:26 UTC
Labels: Type: bug

**Comment by isoos** [comment] 2023-08-25 08:49
> 2023-08-25T05:50:02.343688571Z":

I think this is the weekly backfill triggering it.
