### ISSUE TITLE
Pub is not feeling well 

### ISSUE THREAD

**Issue by Shantanu-07** [dart-lang/pub-dev#4492] opened 2021-02-04 07:41 UTC
Pub is not feeling well .
Fatal package site error.

**Comment by jonasfj** [comment] 2021-02-04 12:11
Thanks for the report :+1: 

The issue should be resolved, closing as duplicate of https://github.com/dart-lang/pub-dev/issues/4485

**Closed by jonasfj** 2021-02-04 12:11 UTC
Labels: Resolution: duplicate
