### ISSUE TITLE
Quick access to UI packages

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [dart-lang/pub-dev#6250] opened 2022-12-06 06:09 UTC
Due to the rich archive of UI packages on this website, It is suggested to have a Tag or Filter for quick access to UI packages.

**Comment by sigurdm** [comment] 2022-12-06 11:05
I think this would be fulfilled with a solution to https://github.com/dart-lang/pub-dev/issues/5219

**Comment by isoos** [comment] 2022-12-14 07:59
Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/5219.

**Closed by isoos** 2022-12-14 07:59 UTC
